package fresh.gui.panels;

import fresh.utilities.Logger;

import javax.swing.*;
import java.awt.*;

// The rest of MainGui is Intellij generated by its SwingDesigner at compile time
public class MainGui {
    private JTabbedPane mainTabbedPane;
    private JPanel mainPanel;
    private JTextField textAField1;

    public void receivePanel(JPanel panel) {
        mainTabbedPane.addTab("test3", panel);
    }
    public JPanel getMainPanel() {
        return this.mainPanel;
    }
}
